### ISSUE TITLE
Updating a module with `report_type` set to "py3o" throws critical error

### ISSUE THREAD

**Issue by osluys** [OCA/reporting-engine#115]
I used the XML example provided in the installation instructions to create a new py3o report in my module, which installed successfully. I was also able to generate an ODF report in Odoo without problems. The issue occurs when I try to **UPDATE** the module (without having changed anything to the report) and get the following critical error in the log file:

```
2017-03-15 15:11:09,140 16327 CRITICAL dev odoo.service.server: Failed to initialize database `dev`.
Traceback (most recent call last):
File "odoo/odoo/service/server.py", line 898, in preload_registries
  registry = Registry.new(dbname, update_module=update_module)
File "odoo/odoo/modules/registry.py", line 78, in new
  odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "odoo/odoo/modules/loading.py", line 335, in load_modules
  force, status, report, loaded_modules, update_module)
File "odoo/odoo/modules/loading.py", line 237, in load_marked_modules
  loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
File "odoo/odoo/modules/loading.py", line 156, in load_module_graph
  _load_data(cr, module_name, idref, mode, kind='data')
File "odoo/odoo/modules/loading.py", line 95, in _load_data
  tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
File "odoo/odoo/tools/convert.py", line 848, in convert_file
  convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
File "odoo/odoo/tools/convert.py", line 918, in convert_xml_import
  obj.parse(doc.getroot(), mode=mode)
File "odoo/odoo/tools/convert.py", line 802, in parse
  self._tags[rec.tag](rec, de, mode=mode)
File "odoo/odoo/tools/convert.py", line 710, in _tag_record
  id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
File "odoo/odoo/addons/base/ir/ir_model.py", line 1153, in _update
  record.write(values)
File "odoo/odoo/addons/base/ir/ir_actions.py", line 47, in write
  res = super(IrActions, self).write(vals)
File "odoo/odoo/models.py", line 3550, in write
  self._write(old_vals)
File "odoo/odoo/models.py", line 3606, in _write
  self._check_selection_field_value(name, val)
File "odoo/odoo/models.py", line 2116, in _check_selection_field_value
  field.convert_to_cache(value, self)
File "odoo/odoo/fields.py", line 1737, in convert_to_cache
  raise ValueError("Wrong value for %s: %r" % (self, value))
ParseError: "Wrong value for ir.actions.report.xml.report_type: 'py3o'" while parsing views/res_partner.xml:7, near
  <record id="partner_report" model="ir.actions.report.xml">
      <field name="name">Some Partner Report</field>
      <field name="model">res.partner</field>
      <field name="report_name">res.partner.some_report</field>
      <field name="report_type">py3o</field>
      <field name="py3o_filetype">odt</field>
      <field name="module">partner_some_report</field>
      <field name="py3o_template_fallback">report/some_report.odt</field>
  </record>
```

I have been able to reproduce this error by uninstalling the module, reinstalling (no error) and then updating (error).

**Comment by lmignon** [comment]
@osluys I've encountered this error one time. In my case I had forgotton to add report_py3 into the 'depends' list of my addon.

**Comment by osluys** [comment]
@lmignon Thanks, your suggestion solved the issue. It didn't even occur to me to add that module as a dependency.
