### ISSUE TITLE
[10.0] report_py3o crash when using the button "Print Invoice" when report as attachement

### ISSUE THREAD

**Issue by alexis-via** [OCA/reporting-engine#119]
Here is the scenario to reproduce the bug on Odoo 10 with an up-to-date reporting-engine branch:
1) install report_py3o and set-it-up to have a py3o invoice with PDF output and keep the default value "(object.state in ('open','paid')) and ('INV'+(object.number or '').replace('/','')+'.pdf')" for the parameter "Save as attachment prefix"
2) Create a new customer invoice. Validate it.
3) On this invoice in "open" state, click on the button "Print Invoice" -> you get the PDF and this PDF is saved as attachement
4) Click on the button "Print Invoice" a second time: you get this crash:
```
2017-03-30 08:44:19,397 1012 INFO test8 odoo.addons.report.models.report: The PDF document INVFA00000399.pdf was loaded from the database
2017-03-30 08:44:19,397 1012 ERROR test8 odoo.service.report: Exception: coercing to Unicode: need string or buffer, tuple found
Traceback (most recent call last):
  File "/home/odoo/erp/odoo/odoo/service/report.py", line 94, in go
    result, format = odoo.report.render_report(cr, uid, ids, object, datas, context)
  File "/home/odoo/erp/odoo/odoo/report/__init__.py", line 19, in render_report
    return env['ir.actions.report.xml'].render_report(ids, name, data)
  File "/home/odoo/erp/reporting-engine/report_py3o/models/ir_actions_report_xml.py", line 92, in render_report
    }).create_report(res_ids, data)
  File "/home/odoo/erp/reporting-engine/report_py3o/models/py3o_report.py", line 360, in create_report
    with open(result_path, 'r+b') as fd:
TypeError: coercing to Unicode: need string or buffer, tuple found
2017-03-30 08:44:19,612 1012 ERROR test8 odoo.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/home/odoo/erp/odoo/addons/web/controllers/main.py", line 68, in wrap
    return f(*args, **kwargs)
  File "/home/odoo/erp/odoo/addons/web/controllers/main.py", line 1468, in index
    request.session.db, request.session.uid, request.session.password, report_id])
  File "/home/odoo/erp/odoo/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/odoo/erp/odoo/odoo/service/report.py", line 35, in dispatch
    res = fn(db, uid, *params)
  File "/home/odoo/erp/odoo/odoo/service/report.py", line 142, in exp_report_get
    return _check_report(report_id)
  File "/home/odoo/erp/odoo/odoo/service/report.py", line 120, in _check_report
    raise UserError('%s: %s' % (exc.message, exc.traceback))
UserError: (u"coercing to Unicode: need string or buffer, tuple found: (<type 'exceptions.TypeError'>, TypeError('coercing to Unicode: need string or buffer, tuple found',), <traceback object at 0x710332c35758>)", None)
```

Note : if you open the attachment from the attachment drop-down menu, you will access the invoice without problems.
In fact, when you have the crash, the variable "result_path" in the method create_report() of report_py3o/models/py3o_report.py contains the binary version of the report (and not a path)...

This regression has probably been introduced recently. @lmignon what do you think about this ? Are you able to reproduce it ?

**Comment by alexis-via** [comment]
With another installation that has up-to-date code, it don't have the crash but I have another problem: when I click a second time on "Print Invoice", it creates a second attachment...

**Comment by sbidoul** [comment]
@alexis-via is it related to https://github.com/OCA/reporting-engine/pull/100?

**Comment by alexis-via** [comment]
@sbidoul It seems to be older than #100 

git co 8b1954e26582ef04ef90bf804a292adb9a8ef0b5  (march 6) => KO -> either crash or create
 double attachements

git co 204afa050a4cba5abd360f3986fd731683f9ff2e (22 fev) => KO, crash with another error msg

git co 9f2ca7d09330e5740d5410e0734656fb02f53bc7 (dec 26) => OK

**Comment by lmignon** [comment]
@alexis-via The 'Reload from Attachment'  functionality is not implemented

**Comment by alexis-via** [comment]
@lmignon OK, so we should consider this as a "missing feature" instead of a pure bug. And maybe we should add a note about it in the README of report_py3o.

**Comment by lmignon** [comment]
@alexis-via :+1:

**Comment by alexis-via** [comment]
@lmignon but, for me, this feature was working in the past (cf my test with the code of December 26)... but maybe it was not working really and was re-generating the invoice, but didn't crash.

**Comment by njeudy** [comment]
@lmignon @alexis-via I don't now why this commit is referenced .. I begin to migrate to V11.0 but it is WIP.
