### ISSUE TITLE
[10.0] report_py3o: ODS to XLS doesn't work

### ISSUE THREAD

**Issue by alexis-via** [OCA/reporting-engine#136]
With an ODS (spreadsheet) template, if I configured to output as XLS with a py3o server, I get an error:

```
2017-05-19 10:17:13,743 31070 ERROR testadl4 odoo.service.report: Exception: (u'Fusion server error {"reasons": ["Renderserver error: ServerError(\'<twisted.python.failure.Failure jpype._jexception.java.lang.NullPointerExceptionPyRaisable: java.lang.NullPointerException>\',)"], "error": true}', None)
Traceback (most recent call last):
  File "/home/odoo/erp/odoo/odoo/service/report.py", line 94, in go
    result, format = odoo.report.render_report(cr, uid, ids, object, datas, context)
  File "/home/odoo/erp/odoo/odoo/report/__init__.py", line 19, in render_report
    return env['ir.actions.report.xml'].render_report(ids, name, data)
  File "/home/odoo/erp/reporting-engine/report_py3o/models/ir_actions_report_xml.py", line 98, in render_report
    }).create_report(res_ids, data)
  File "/home/odoo/erp/reporting-engine/report_py3o/models/py3o_report.py", line 354, in create_report
    model_instances, data, save_in_attachment))
  File "/home/odoo/erp/reporting-engine/report_py3o/models/py3o_report.py", line 278, in _create_single_report
    _('Fusion server error %s') % r.text,
UserError: (u'Fusion server error {"reasons": ["Renderserver error: ServerError(\'<twisted.python.failure.Failure jpype._jexception.java.lang.NullPointerExceptionPyRaisable: java.lang.NullPointerException>\',)"], "error": true}', None)
```

**Comment by alexis-via** [comment]
I confirm that the package "libreoffice-calc" is installed. The logs of the fusion server say:

```
2017-05-19 12:35:18,810 INFO server py3o.fusion server starting
2017-05-19 12:35:18,812 INFO server listing on port: 8765
2017-05-19 12:35:45,493 INFO formpage Request received launching thread
2017-05-19 12:35:46,449 INFO formpage rendering thread finished for target xls
2017-05-19 12:35:46,449 INFO formpage Errors sent to client --> ["Renderserver error: ServerError('<twisted.python.failure.Failure jpype._jexception.java.lang.NullPointerExceptionPyRaisable: java.lang.NullPointerException>',)"]
```

**Comment by jr1003** [comment]
I have the same problem, also can't generate ODS --> PDF .. help us pls..

**Comment by alexis-via** [comment]
When I connect directly to py3o fusion (http://localhost:8765/form) and use the test form to test the rendering:
- ODS -> ODS work fine
- ODS -> XLS doesn't work and produce the same error in the py3o.fusion logs.

So my analysis is that the problem is located in py3o.fusion or py3o.renderserver and not in the Odoo module report_py3o.

**Comment by alexis-via** [comment]
I opened a bug report on py3o.renderserver: https://bitbucket.org/faide/py3o.fusion/issues/2/ods-xls-conversion-doesnt-work

**Comment by jr1003** [comment]
@alexis-via hi..o/ you have any solution for this???

**Comment by alexis-via** [comment]
@jr1003 No, I didn't find the solution so far. If you have some ideas to fix this, please comment on the bug report here or on bitbucket.

**Comment by jr1003** [comment]
@alexis-via one question.. you can convert ODS --> PDF????

**Comment by alexis-via** [comment]
I have not tested ODS -> PDF, because I only need ODS -> XLS, so I don't know if ODS -> PDF works.

**Comment by jr1003** [comment]
=S .. any idea to fixed ????

**Comment by elicoidal** [comment]
I have pushed a workaround [here](https://github.com/Elico-Corp/odoo-addons/tree/10.0/report_py3o_convert_xlsx) that works fine for us, using libreoffice to render the XLSX file.

Ideally of course the best would be to solve the original bug.

**Comment by jr1003** [comment]
@elicoidal omg.. ty.. it´s work.. // .. one question.. you can convert ods to pdf ?.. i only can odt --> pdf

**Comment by elicoidal** [comment]
@jr1003 It does not right now but it should not be difficult to achieve.
You would need to adapt the module: add a field for the desired output format (xls or pdf) and call the proper method of libreoffice accordingly.

**Comment by jr1003** [comment]
@elicoidal  ty .. really.. ty so much..

**Comment by elicoidal** [comment]
hope it helps! (until we can get the actual bug fixed :wink:
