### ISSUE TITLE
[10.0] report_py3o_fusion_server breaks simple reports

### ISSUE THREAD

**Issue by alexis-via** [OCA/reporting-engine#200]
Since the merge of the big PR https://github.com/OCA/reporting-engine/pull/180 by @hbrunn , there are several breakages when using report_py3o_fusion_server.

Here is one example:
1) install report_py3o
2) install stock_inventory_valuation_ods from https://github.com/akretion/odoo-usability/tree/10.0/stock_inventory_valuation_ods (it depends on stock_inventory_valuation from https://github.com/akretion/odoo-addons-grap/tree/10-port-stock_inventory_valuation/stock_inventory_valuation)
3) Go to the menu Inventory > Inventory Adjustments, select any inventory and do "Print > Inventory Valuation (ODS)" => It works, you get an ODS file
4) Install the module report_py3o_fusion_server
5) Repeat step 3: it breaks:

```
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/reporting-engine0/report_py3o/controllers/main.py", line 84, in report_download
    reportname, docids=docids, converter='py3o')
  File "/home/alexis/new_boite/dev/odoo0/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/alexis/new_boite/dev/reporting-engine0/report_py3o/controllers/main.py", line 52, in report_routes
    res, filetype = py3o_report.create_report(docids, data)
  File "/home/alexis/new_boite/dev/reporting-engine0/report_py3o/models/py3o_report.py", line 374, in create_report
    model_instance, data, save_in_attachment))
  File "/home/alexis/new_boite/dev/reporting-engine0/report_py3o/models/py3o_report.py", line 315, in _get_or_create_single_report
    model_instance, data, save_in_attachment)
  File "/home/alexis/new_boite/dev/reporting-engine0/report_py3o_fusion_server/models/py3o_report.py", line 71, in _create_single_report
    report_xml.py3o_server_id.url, data=fields, files=files)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 353, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL 'False': No schema supplied. Perhaps you meant http://False?
```

**Comment by hbrunn** [comment]
we probably need another conditional to just call super when there's no server defined in https://github.com/OCA/reporting-engine/pull/180/files#diff-ae25dd9608ed1c968919639e1efd38c5R35 right?

**Comment by alexis-via** [comment]
I'm not familiar at all with that kind of code, so I can't say about the solution. But if you think you can fix it, it would be really great, because it's a bad regression. In the meantime, I don't upgrade the code of OCA/reporting-engine for my users on v10.

**Comment by hbrunn** [comment]
I thought you were the author of this module? That's why I was a bit confused that you'd file a bug report instead of just a PR. I didn't change so much of the code actually, just moved around and refactored. Anyways, I'm waiting for a build to finish and #201 should fix this.

If you're up for a horse trade, how about https://github.com/OCA/edi/pull/11 ?
