### ISSUE TITLE
[10.0] Can't print report under attachment

### ISSUE THREAD

**Issue by nathchan** [OCA/reporting-engine#203]
Uncaught SyntaxError: Unexpected end of JSON input
http://3319758-10-0-a694e5.runbot2.odoo-community.org/web?debug=1#id=1&view_type=form&model=res.users&menu_id=65&action=71:1
Traceback:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.<anonymous> (http://3319758-10-0-a694e5.runbot2.odoo-community.org/web/content/344-b7c1c9e/web.assets_common.js:3043:379)
    at HTMLIFrameElement.dispatch (http://3319758-10-0-a694e5.runbot2.odoo-community.org/web/content/344-b7c1c9e/web.assets_common.js:637:451)
    at HTMLIFrameElement.elemData.handle (http://3319758-10-0-a694e5.runbot2.odoo-community.org/web/content/344-b7c1c9e/web.assets_common.js:610:173)

**Comment by pedrobaeza** [comment]
Modules? Steps to reproduce? Version? With this barely info is impossible to solve anything.

**Comment by nathchan** [comment]
http://3319758-10-0-a694e5.runbot2.odoo-community.org/web?debug=1#id=3&view_type=form&model=account.invoice&menu_id=168&action=238
I tested creating one invoice template (maybe not correct setting) on Module py3o report engine --> Accounting --> Customer Invoices --> Open an invoice --> Print --> Nath Py3o Demo Report

**Comment by pedrobaeza** [comment]
Sorry, but you probably not set correctly the template, so this is not something you have to publish here, but on forums.

**Comment by nathchan** [comment]
Is there sample settings?

**Comment by pedrobaeza** [comment]
I suppose in Py3o library.
