### ISSUE TITLE
[10.0] report_py3o Error updating from  10.0.1.1.0 -->> 10.0.2.0.1

### ISSUE THREAD

**Issue by collex100** [OCA/reporting-engine#210]
report_py3o Error updating from  10.0.1.1.0 -->> 10.0.2.0.1

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1334, in load_views
    for [v_id, v_type] in views
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1334, in <dictcomp>
    for [v_id, v_type] in views
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/module/module.py", line 139, in fields_view_get
    res = super(Module, self).fields_view_get(view_id, view_type, toolbar=toolbar, submenu=False)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 1426, in fields_view_get
    resprint = IrValues.get_actions('client_print_multi', self._name)
  File "<decorator-gen-25>", line 2, in get_actions
  File "/usr/lib/python2.7/site-packages/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_values.py", line 415, in get_actions
    for field in fields
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_values.py", line 415, in <dictcomp>
    for field in fields
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 5208, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 910, in __get__
    self.determine_value(record)
  File "/usr/lib/python2.7/site-packages/odoo/fields.py", line 1012, in determine_value
    record._prefetch_field(self)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3063, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3007, in read
    self._read_from_database(stored, inherited)
  File "/usr/lib/python2.7/site-packages/odoo/models.py", line 3131, in _read_from_database
    cr.execute(query_str, params)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column ir_act_report_xml.py3o_multi_in_one does not exist
LINE 1: ...eport_rml","ir_act_report_xml"."multi" as "multi","ir_act_re...
                                                             ^
```

Help me please. I can not update the module.

**Comment by pedrobaeza** [comment]
But are you really updating the module, or just loading the new code version?

**Comment by collex100** [comment]
Removed the old version. Uploaded a new version. Restarted odoo. And I got such a mistake.

**Comment by pedrobaeza** [comment]
That's not enough. You need to update the module via command line with `-u <module>`

**Comment by collex100** [comment]
Thanks!
