### ISSUE TITLE
[10.0][bi_view_editor] If model name has apostrophe can't generate view

### ISSUE THREAD

**Issue by SimoRubi** [OCA/reporting-engine#231]
Steps:
1. Go to model's tree in Technical > database structure > model;
2. Change a model's name to introduce an apostrophe (e.g. Account -> Account's model)
3. In Dashboard > Custom BI View, create a new view and select a field from the model just edited and save
4. Generate view and get  
<details><summary>Error</summary>
<p>

`Odoo Server Error`

```
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-10.0/addons/web/controllers/main.py", line 884, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/build/OCA/reporting-engine/bi_view_editor/models/bve_view.py", line 352, in action_create
    self._create_sql_view()
  File "/home/odoo/build/OCA/reporting-engine/bi_view_editor/models/bve_view.py", line 288, in _create_sql_view
    formatted_data = json.loads(self._get_format_data(self.data))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 1 column 54 (char 53)
```

</p>
</details>

**Comment by SimoRubi** [comment]
Solved by https://github.com/OCA/reporting-engine/pull/232
