### ISSUE TITLE
error when new py3o report

### ISSUE THREAD

**Issue by thomaspot** [OCA/reporting-engine#294]
Issue: Odoo Version 12 / report_py3o
tested on V12 Enterprise edition.

goto Settings -> Technical - Reporting -> reports.
Add a new report, choose report_type = p3o 

When adding a new Py3O Report we get following error:

When bypassing (setting it forced) I can create a report and also a template. It works fine afterwards.
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: <odoo.models.NewId object at 0x7fd7311f8d98>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/home/odoo/src/odoo/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.actions.report(<odoo.models.NewId object at 0x7fd7311f8d98>,).is_py3o_report_not_available', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: <odoo.models.NewId object at 0x7fd7311f8d98>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/home/odoo/src/odoo/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.actions.report(<odoo.models.NewId object at 0x7fd7311f8d98>,).is_py3o_native_format', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 5498, in onchange
    snapshot1 = Snapshot(record, nametree)
  File "/home/odoo/src/odoo/odoo/models.py", line 5388, in __init__
    if subnames else record[name]
  File "/home/odoo/src/odoo/odoo/models.py", line 5097, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/odoo/fields.py", line 987, in __get__
    self.determine_draft_value(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1109, in determine_draft_value
    self._compute_value(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1043, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/src/user/OCA/reporting-engine/report_py3o/models/ir_actions_report.py", line 140, in _compute_py3o_report_not_available
    if not rec.is_py3o_native_format and not rec.lo_bin_path:
  File "/home/odoo/src/odoo/odoo/fields.py", line 987, in __get__
    self.determine_draft_value(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1109, in determine_draft_value
    self._compute_value(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1043, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/src/user/OCA/reporting-engine/report_py3o/models/ir_actions_report.py", line 126, in _compute_is_py3o_native_format
    rec.is_py3o_native_format = format.get_format(filetype).native
  File "/home/odoo/.local/lib/python3.6/site-packages/py3o/formats/main.py", line 67, in get_format
    raise UnkownFormatException("Format {} is unkown".format(name))
py3o.formats.main.UnkownFormatException: Format False is unkown
```

**Comment by rachmataditiya** [comment]
same problem here, I can produce it

**Comment by lmignon** [comment]
@thomaspot @rachmataditiya Can you describe the steps to reproduce this problem? Reading the code, this bug could occurs if you don't specify an outptut format into your report definition. This field should be required for report of type 'py3o'.

**Comment by rachmataditiya** [comment]
at first time you create a report there's no default definition at form. workaround is to set default output type into the field

**Comment by lmignon** [comment]
@rachmataditiya PR to fix this issue is welcome :smirk:

**Comment by rachmataditiya** [comment]
> @rachmataditiya PR to fix this issue is welcome

I've submitted pull request here https://github.com/OCA/reporting-engine/pull/303#issue-293274501

**Comment by diezcode** [comment]
still there, any solution?
I still getting this error:
`Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/src/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/src/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/models.py", line 5516, in onchange
    for name in nametree
  File "/home/odoo/src/odoo/odoo/models.py", line 5517, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/home/odoo/src/odoo/odoo/models.py", line 5419, in has_changed
    return self[name] != record[name]
  File "/home/odoo/src/odoo/odoo/models.py", line 5120, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/odoo/fields.py", line 995, in __get__
    self.determine_draft_value(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1117, in determine_draft_value
    self._compute_value(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1051, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/src/user/report_py3o/models/ir_actions_report.py", line 153, in _compute_py3o_report_not_available
    if not rec.is_py3o_native_format and not rec.lo_bin_path:
  File "/home/odoo/src/odoo/odoo/fields.py", line 995, in __get__
    self.determine_draft_value(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1117, in determine_draft_value
    self._compute_value(record)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1051, in _compute_value
    getattr(records, self.compute)()
  File "/home/odoo/src/user/report_py3o/models/ir_actions_report.py", line 139, in _compute_is_py3o_native_format
    rec.is_py3o_native_format = format.get_format(filetype).native
  File "/home/odoo/.local/lib/python3.6/site-packages/py3o/formats/main.py", line 67, in get_format
    raise UnkownFormatException("Format {} is unkown".format(name))
py3o.formats.main.UnkownFormatException: Format False is unkown`

I used the new modul with "this fix that don't works for me"
