### ISSUE TITLE
[12.0] report_qweb_signer TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by jchanme** [OCA/reporting-engine#385]
After installing this module and set a record to apply to Sale Order model in company setting, there is an error after I set the "Save as attachment" to `(object.name or '').replace('/','_') + '.signed.pdf'`. This happened only when I print report of send by email the second time. First time it was fine. Below is the error message:` Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-12/addons/web/controllers/main.py", line 1671, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/opt/odoo/odoo-12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons-test/report_xlsx/controllers/main.py", line 59, in report_routes
    reportname, docids, converter, **data
  File "/opt/odoo/odoo-12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-12/addons/web/controllers/main.py", line 1613, in report_routes
    pdfhttpheaders = [('Content-Type', 'application/pdf'), ('Content-Length', len(pdf))]
TypeError: object of type 'int' has no len()`

Has anyone experienced the same problem? How do you solve this?

**Comment by jchanme** [comment]
Hello! Is this considered an issue? Do you experience the same?

**Comment by PauliusP17** [comment]
Having the same issue with 13.0, when you you use the "print_report_name" attribute, the print fails with the exact same error.
One thing to note is that this is happening when the "model" of the report is a TransientModel.
