### ISSUE TITLE
[13.0] this._super.apply(...).finally is not a function

### ISSUE THREAD

**Issue by KirillKriachenko** [OCA/reporting-engine#433]
Odoo 13. After downloading and installing Base report xlsx V13. When I download report odoo displays this Client Error, but still generates and load Excel file.

Traceback:
TypeError: this._super.apply(...).finally is not a function
    at Class._handleAction (http://localhost:8070/web/content/408-7574f36/web.assets_backend.js:3219:1035)
    at Class._handleAction (http://localhost:8070/web/content/353-af4cd92/web.assets_common.js:3863:371)
    at http://localhost:8070/web/content/408-7574f36/web.assets_backend.js:410:185

**Comment by legalsylvain** [comment]
Hi can you reproduce it on runbot ? Thanks.

**Comment by KirillKriachenko** [comment]
Sure. Just explain how to work with runbot . If I call it from my custom module how can I reproduce it?

**Comment by legalsylvain** [comment]
Hi. You have to 
- go to the runbot of the OCA :https://runbot.odoo-community.org/runbot/repo/https-github-com-oca-reporting-engine-143
- select the correct version. 
- try to reproduce the bug on the instance.

AFAIK, you can not test custom modules on runbot.

**Comment by ytlimin** [comment]
I hit the same error too, today, I just downloaded Base report xlsx V13 from github, 

TypeError: this._super.apply(...).finally is not a function
    at Class._handleAction (http://localhost:8469/web/content/2662-30079d5/web.assets_backend.js:3727:1032)
    at Class._handleAction (http://localhost:8469/web/content/2659-2b76ed9/web.assets_common.js:4549:371)
    at http://localhost:8469/web/content/2662-30079d5/web.assets_backend.js:412:185
