### ISSUE TITLE
Error on report_xml with module l10n_es_facturae

### ISSUE THREAD

**Issue by daviddoradocarvajal** [OCA/reporting-engine#641]
module: report_xml
version: 15.0

Hello, my problem is the following:
- Odoo version: 15 community (docker container)
- Postgres version: 13 (docker container)
When trying to create an xml with an invoice in the module l10n_es_facturae (https://odoo-community.org/shop/creacion-de-factura-e-763?search=l10n_es_facturae#attr=19450) the following error appears:

RPC_ERROR
Odoo Server Error

Traceback (most recent call last): File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch result = request.dispatch()   File "/usr/lib/python3/dist-packages/odoo/http.py", line 688, in dispatch result = self._call_function(**self.params) File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function return checked_call(self.db, *args, **kwargs) File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper return f(dbname, *args, **kwargs) File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call result = self.endpoint(*a, **kw) File "/usr/lib/python3/dist-packages/odoo/http.py", line 917, in __call__ return self.method(*args, **kw) File "/usr/lib/python3/dist-packages/odoo/http.py", line 535, in response_wrap response = f(*args, **kw) File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1351, in call_button action = self._call_kw(model, method, args, kwargs) File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1339, in _call_kw return call_kw(request.env[model], method, args, kwargs) File "/usr/lib/python3/dist-packages/odoo/api.py", line 464, in call_kw result = _call_kw_multi(method, model, args, kwargs) File "/usr/lib/python3/dist-packages/odoo/api.py", line 451, in _call_kw_multi result = method(recs, *args, **kwargs) File "/mnt/extra-addons/l10n_es_facturae/wizard/create_facturae.py", line 65, in create_facturae_file move_file = self.env.ref("l10n_es_facturae.report_facturae")._render( File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 915, in _render return render_func(res_ids, data=data) File "/mnt/extra-addons/report_xml/models/ir_actions_report.py", line 59, in _render_qweb_xml content, ttype = report_model.generate_report( File "/mnt/extra-addons/report_xml/reports/report_report_xml_abstract.py", line 59, in generate_report parsed_result_bin = minidom.parseString(result_bin) File "/usr/lib/python3.9/xml/dom/minidom.py", line 1998, in parseString return expatbuilder.parseString(string) File "/usr/lib/python3.9/xml/dom/expatbuilder.py", line 925, in parseString return builder.parseString(string) File "/usr/lib/python3.9/xml/dom/expatbuilder.py", line 223, in parseString parser.Parse(string, True) Exception The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/lib/python3/dist-packages/odoo/http.py", line 644, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception raise exception.with_traceback(None) from new_cause xml.parsers.expat.ExpatError: mismatched tag: line 144, column 57

Through the logs I have noticed that the file generates it but the error is still there and does not allow me to download it.
I have done the same test in Odoo 14 community and it works perfectly but I need to install it on Odoo 15

I have tried to put an issue in the l10n_es repository also but without success so as in the trace appears this module I also try it here and any help will be welcome.
Sorry for my bad English im using a translator (I'm Spanish)

**Comment by daviddoradocarvajal** [comment]
Problem solved, the problem was on l10n_es_facturae. Thank you all and sorry for the unnecessary ticket
