### ISSUE TITLE
View error for KPI dashboard on 15.0

### ISSUE THREAD

**Issue by miquelrosell99** [OCA/reporting-engine#689]
Error: No view found for act_window action 2711
    at _executeActWindowAction (http://erp.gmidental.com:8069/web/assets/2749-dc7d04b/web.assets_backend.min.js:2277:25)
    at doAction (http://erp.gmidental.com:8069/web/assets/2749-dc7d04b/web.assets_backend.min.js:2301:8)
    at async Object.loadState (http://erp.gmidental.com:8069/web/assets/2749-dc7d04b/web.assets_backend.min.js:2320:322)
    at async WebClient.loadRouterState (http://erp.gmidental.com:8069/web/assets/2749-dc7d04b/web.assets_backend.min.js:2457:41)

**Comment by legalsylvain** [comment]
Did you reproduce the bug on runboat ?
