### ISSUE TITLE
UnboundLocalError: local variable 'reportname' referenced before assignment

### ISSUE THREAD

**Issue by jerzyk** [OCA/reporting-engine#694]
## Module
report_xlsx

## Describe the bug
exception during system update (-u base)

in report_xlsx/controllers/main.py line 101 there is a reference to @reporname@ valiarble which may not be yet set, soution will be to declare valiable before try-except block

**Comment by Protoneer** [comment]
Having the same issue.


Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1986, in __call__
    response = request._serve_db()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1721, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/mnt/extra-addons/oca/report_xlsx/controllers/main.py", line 101, in report_download
    _logger.exception("Error while generating report %s", reportname)
UnboundLocalError: local variable 'reportname' referenced before assignment

**Comment by Protoneer** [comment]
For me this ended up being that the report actions was setup as PDF instead of XLSX.  Before the above error there was another saying that it was looking for "_get_report_values" that was the clue to me resolving it.
