### ISSUE TITLE
[15.0] [BUG] bi_sql_editor Can't delete SQL view

### ISSUE THREAD

**Issue by jabelchi** [OCA/reporting-engine#721]
## Module
bi_sql_editor

## Describe the bug
An error is raised when atempting to delete a view. 

## To Reproduce
**Affected versions**: V15 

1. Set an SQL view to "draft" state.
2. Click on Action / Delete
3. An error is raised (look below)

**Expected behavior**
The view is deleted from Odoo.

**ERROR TRACE**
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1347, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1339, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo_base_mdg/OCA/reporting-engine/bi_sql_editor/models/bi_sql_view.py", line 262, in unlink
    self.cron_id.unlink()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_cron.py", line 382, in unlink
    self._try_lock(lockfk=True)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_cron.py", line 363, in _try_lock
    self._cr.execute(f"""
  File "<decorator-gen-3>", line 2, in execute
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.SyntaxError: error de sintaxis en o cerca de «)»
LÍNEA 4:                 WHERE id IN ()
                                      ^

**Comment by legalsylvain** [comment]
Thanks for reporting.
is it regarding view that was confirmed before ? if yes, it is materialized or not views ?

**Comment by jabelchi** [comment]
The view was confirmed and is not materialized.
