### ISSUE TITLE
TypeError: this._super.apply(...).finally is not a function (report_xlsx Odoo 13)

### ISSUE THREAD

**Issue by AntonBalmakov** [OCA/reporting-engine#782]
## Module
report_xlsx

## Describe the bug
TypeError: this._super.apply(...).finally is not a function

## To Reproduce
**Affected versions**: 13.0.1.0.1

1.report.xml

```
<odoo>   
  <report
          id="project_project_material_statistics"
          model="la.projects"
          string="Project material statistics (.xlsx)"
          report_type="xlsx"
          name="la_projects.material_statistics_xlsx"
          file="project_material_statistics"
          attachment_use="False"/>
</odoo>
```

2.python file (project_material_statistics.py)
```
class MaterialStatisticsXlsx(models.AbstractModel):
    _name = 'report.la_projects.material_statistics_xlsx'
    _inherit = 'report.report_xlsx.abstract'
    _description = 'Report la projects report material statistics xlsx'

    def generate_xlsx_report(self, workbook, data, objects):
        report_name = "Material statistics report"
        worksheet = workbook.add_worksheet(report_name)
        worksheet.set_column('A:H', 15)
      
        columns = ['Name', 'Internal Reference', 'Thikness', 'Length',
                   'Width', 'Texture Direction ', 'Bilateral Material', 'Sign']

        row = 0
        col = 0

        for column in columns:
            worksheet.write(row, col, column)
            col += 1
```

3. print ->Project material statistics (.xlsx)
The report is created and downloaded, but on my odoo13 version I get an error. 

```
Traceback:
TypeError: this._super.apply(...).finally is not a function
    at Class._handleAction (http://localhost:8069/web/content/3545-4359196/web.assets_backend.js:3392:1035)
    at Class._handleAction (http://localhost:8069/web/content/2788-9b8f57e/web.assets_common.js:3864:371)
    at http://localhost:8069/web/content/3545-4359196/web.assets_backend.js:411:185
```

**Expected behavior**
I expect the report to download without error. 

**Additional context**
Os Linux, Python 3.8

**Comment by AntonBalmakov** [comment]
And now I'm getting a different error 

Uncaught TypeError: Cannot read properties of undefined (reading 'apply')
http://localhost:8069/web/content/3545-4359196/web.assets_backend.js:3398
Traceback:
TypeError: Cannot read properties of undefined (reading 'apply')
    at Object.error (http://localhost:8069/web/content/3545-4359196/web.assets_backend.js:3398:150)
    at xhr.onerror (http://localhost:8069/web/content/2788-9b8f57e/web.assets_common.js:3841:106)
