### ISSUE TITLE
[14] get_report_xlsx() missing 4 required positional arguments

### ISSUE THREAD

**Issue by whotopia** [OCA/reporting-engine#802]
[14.0] report_xlsx no longer working for me 

## Module
report_xlsx

## Describe the bug
Every time I try to run an Excel report for OCA Reporting General Ledger, I am getting error message.  

## To Reproduce
**Affected versions**:  Odoo 14.   

In my case it is happening all the time.  Likely interaction with something else.    

Here's my error message:
```

Traceback (most recent call last):
  File "/home/odoo/odoo-venv-3.8/lib/python3.8/site-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/home/odoo/odoo-venv-3.8/lib/python3.8/site-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 1298, in __call__
    return self.dispatch(environ, start_response)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 1264, in __call__
    return self.app(environ, start_wrapped)
  File "/home/odoo/odoo-venv-3.8/lib/python3.8/site-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 1489, in dispatch
    result = ir_http._dispatch()
  File "/home/odoo/src/odoo-14.0-OCB/addons/website_sale/models/ir_http.py", line 15, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo-14.0-OCB/addons/website/models/ir_http.py", line 183, in _dispatch
    response = super(Http, cls)._dispatch()
  File "/home/odoo/src/odoo-14.0-OCB/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/home/odoo/src/odoo-14.0-OCB/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo-14.0-OCB/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo-14.0-OCB/addons/http_routing/models/ir_http.py", line 512, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/home/odoo/src/odoo-14.0-OCB/odoo/addons/base/models/ir_http.py", line 241, in _dispatch
    return cls._handle_exception(e)
  File "/home/odoo/src/odoo-14.0-OCB/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/home/odoo/src/odoo-14.0-OCB/addons/http_routing/models/ir_http.py", line 607, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception
    return request._handle_exception(exception)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 757, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo-14.0-OCB/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: get_report_xlsx() missing 4 required positional arguments: 'model', 'options', 'output_format', and 'report_name' - - -

```
**Assistance**
I did also note that this issue was (seemingly) also reported here and could be similar:  https://www.odoo.com/forum/help-1/i-have-an-issue-in-odoo-14-versio-in-generating-the-exel-file-219672

This is probably something to do with some kind of other interaction.  Could someone suggest where I might look?

**Comment by imohamed-rizwan** [comment]
The same for me; up until I installed a new reporting module (perhaps OCA and other premium ones as well), I had no problems with freshly added data (let's suppose "Attendance.xlsx"). The identical error for 'Attendance.xlsx' is being encountered after installing any external reporting modules.

After uninstalling the module, it functions properly.

**Comment by imohamed-rizwan** [comment]
@pedrobaeza kindly have a look!

**Comment by pedrobaeza** [comment]
I don't experiment such problem. Update the code for all sources.
