### ISSUE TITLE
Custom report filenames Bug

### ISSUE THREAD

**Issue by Kanzll** [OCA/reporting-engine#85]
Hello,

I get this error after installing report_custom_filename module:
---------
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20151213\server\.\openerp\http.py", line 537, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20151213\server\.\openerp\http.py", line 1415, in _dispatch_nodb
  File "werkzeug\routing.pyc", line 1433, in match
NotFound: 404: Not Found
---------
 I have 8.0-20151213 odoo version

Txs for your job.

module: report_custom_filename
version: 8.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by pedrobaeza** [comment]
Restart your server to see, but the module is not causing that problem for sure.

**Comment by Kanzll** [comment]
Yes, It's Worked.
Thank you
